### ISSUE TITLE
js api client

### ISSUE THREAD

**Issue by siutsin** [colloquet/lihkg-web#3]
Inspired by your API code, I have published a npm package helping js developers to get the threads from lihkg [https://github.com/siutsin/lihkg-api-nodejs-client](https://github.com/siutsin/lihkg-api-nodejs-client).

Since I will continue adding the APIs for it, do you want a PR to integrate this lib with `lihkg-web`?

**Comment by colloquet** [comment]
Hi brother! Sorry for the late reply, I am not in Hong Kong at the moment. Good work on the npm package! Since there are basically only 3 urls to load, I am not sure if it's a good idea to install another package for it, if in the future I decide to add login functionality in to the app then maybe it will be a good idea then! Awesome work anyway!

**Comment by siutsin** [comment]
No worries, this is just a very fresh lib idea. I will continue adding the rest of the API request over the weekend when I have time.
